name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout shape files
      uses: actions/checkout@v2

    - name: Get Git Version
      uses: docker://gittools/gitversion:5.0.2-linux-centos-7-netcoreapp2.2
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_MajorMinorPatch > /github/workspace/version.txt\""
    - run: echo /github/workspace/version.txt

    - name: Setup the PhantomJS enviroment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: phantomjs --version
    - run: find ./shapes/ -name '*.shape' -exec ./scripts/generateShape.sh {} \;
      env:
        CI: true


    - name: Generate Release ZIP file
      run: zip -r brainbox-shapes ./shapes


    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false


    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./brainbox-shapes.zip
        asset_name: brainbox-shapes.zip
        asset_content_type: application/zip


    - name: Commit generated files into github
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Andreas Herz
        author_email: a.herz@freegroup.de
        message: "Generate JS, Documentation and thumbnail from .shape file"
        add: "shapes"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

